### ISSUE TITLE
[#A] Nutritional content of different foods

### ISSUE THREAD

**Issue by philippaSteinberg** [philippaSteinberg/EEP153-Proj2#7]
For all the foods you're considering you'll need to be able to describe their nutritional content, in terms that allow you to compare with recommended daily allowances. We'll provide pointers to US government recommendations, but many other countries have their own recommendations, which may be better suited to their populations.

**Comment by philippaSteinberg** [comment]
Nutrition value recommendations for middle schoolers
[NSLP and SBP Meal Patterns - Healthy Eating & Nutrition Education (CA Dept of Education)](https://www.cde.ca.gov/ls/nu/he/smi.asp)

**Comment by philippaSteinberg** [comment]
Middle school lunch schedule https://www.ousd.org/cms/lib/CA01001176/Centricity/Domain/6652/February%202023%20K8%20Satellite%20Menu.pdf

**Comment by philippaSteinberg** [comment]
Typical lunch:
- Cheese Burger
- 1% fat milk 
- Daily Produce Bar with a combination of:
Red Apples, Edamame, Mini Carrots, Mandarins
Harvest of the Month: Cauliflower, Celery Sticks,
Bosc Pears, Oranges, Jicama Sticks, Spinach,
Kiwis, and Bartlett Pears

**Comment by oghomiep** [comment]
cheese burger
- ground beef
- american cheese
- burger bun

**Comment by philippaSteinberg** [comment]
@max177777 
#%pip install -r requirements.txt
apikey = "ZjI8IO8och2IcbrktkDdNCoCYmQLILJaLMQh6NB2"
import pandas as pd
from eep153_tools.sheets import read_sheets

df = read_sheets("https://docs.google.com/spreadsheets/d/1Ml9KIH_HLl64Y8zTldoghUu5ZhTY7IXanN77itVAxRM/edit#gid=0",
                 sheet='prices')

df = df.set_index('Food')
df = df.reset_index()
df
D = {}
count = 0
for food in  df.Food.tolist():
    try:
        FDC = df.loc[df.Food==food,:].FDC[count]
        count+=1
        D[food] = fdc.nutrients(apikey,FDC).Quantity
    except AttributeError: 
        warnings.warn("Couldn't find FDC Code %s for food %s." % (food,FDC))        

FoodNutrients = pd.DataFrame(D,dtype=float)

**Comment by philippaSteinberg** [comment]
Nutrient table: 
[FoodNutrients.csv](https://github.com/philippaSteinberg/EEP153-Proj2/files/10865865/FoodNutrients.csv)

**Comment by max177777** [comment]
The test sheet to run the code
https://docs.google.com/spreadsheets/d/16mBZiYIfJG0HUg9hei7Yh8On3unVLqzbAl3WUHmfbWg/edit#gid=0
